// This file is generated by Prismic local builder. Update with care!

export { default as GalleryImage } from './GalleryImage'
export { default as NewSlice } from './NewSlice'
export { default as TextSlice } from './TextSlice'
